package com.example.tisunga.ui.navigation

object Routes {
    const val WELCOME = "welcome"
    const val SIGN_IN = "sign_in"
    const val CREATE_ACCOUNT = "create_account"
    const val VERIFICATION = "verification"
    const val CREATE_PASSWORD = "create_password"
    const val FORGOT_PASSWORD = "forgot_password"
    const val HOME = "home"
    const val GROUP_DETAIL = "group_detail/{groupId}"
    const val GROUP_MEMBERS = "group_members/{groupId}"
    const val GROUP_MEMBERS_CHAIR = "group_members_chair/{groupId}"
    const val CREATE_GROUP_STEP1 = "create_group_step1"
    const val ADD_MEMBERS = "add_members/{groupId}"
    const val DISCOVER_GROUPS = "discover_groups"
    const val JOIN_GROUP = "join_group"
    const val GROUP_SAVINGS = "group_savings"
    const val MAKE_CONTRIBUTION = "make_contribution/{groupId}"
    const val CONTRIBUTION_HISTORY = "contribution_history/{groupId}"
    const val DISBURSEMENT = "disbursement/{groupId}"
    const val ALL_LOANS = "all_loans"
    const val MY_LOANS = "my_loans/{groupId}"
    const val GROUP_LOANS = "group_loans/{groupId}"
    const val GROUP_LOANS_DETAIL = "group_loans_detail/{groupId}"
    const val APPLY_LOAN = "apply_loan/{groupId}"
    const val EVENTS = "events/{groupId}"
    const val TRANSACTIONS = "transactions/{groupId}"
    const val NOTIFICATIONS = "notifications"
    const val USER_PROFILE = "user_profile"
}
